import os
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.units import inch
from datetime import datetime

class PdfService:
    def __init__(self, static_dir: str = "app/static"):
        self.static_dir = static_dir
        os.makedirs(self.static_dir, exist_ok=True)

    def generate_report(self, user_data: dict, recommendation: str) -> str:
        """
        Generates a PDF report for the user and returns the relative file path.
        """
        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
        print(f"📄 Starting PDF Generation for {user_data.get('name')} at {timestamp}")
        filename = f"Insurance_Plan_{user_data.get('name', 'User').replace(' ', '_')}_{timestamp}.pdf"
        filepath = os.path.join(self.static_dir, filename)

        doc = SimpleDocTemplate(
            filepath,
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )

        styles = getSampleStyleSheet()
        
        # Custom Styles
        styles.add(ParagraphStyle(
            name='Header1',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#2563eb'),
            spaceAfter=30,
            alignment=1 # Center
        ))
        
        styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#1e40af'),
            spaceBefore=20,
            spaceAfter=10
        ))
        
        styles.add(ParagraphStyle(
            name='NormalText',
            parent=styles['Normal'],
            fontSize=12,
            leading=16,
            spaceAfter=10
        ))

        story = []

        # 1. Header
        story.append(Paragraph("Suraksha Sahayak", styles['Header1']))
        story.append(Paragraph(f"Personalized Insurance Plan Report", styles['Title']))
        story.append(Paragraph(f"Date: {datetime.now().strftime('%B %d, %Y')}", styles['Normal']))
        story.append(Spacer(1, 20))

        # 2. User Profile Table
        story.append(Paragraph("📋 User Profile", styles['SectionHeader']))
        
        data = [
            ["Attribute", "Details"],
            ["Name", user_data.get('name', 'N/A')],
            ["Age", user_data.get('age', 'N/A')],
            ["Gender", user_data.get('gender', 'N/A')],
            ["Occupation", user_data.get('occupation', 'N/A')],
            ["Dependents", user_data.get('family', 'N/A')],
            ["Primary Concern", user_data.get('worry', 'N/A')]
        ]
        
        t = Table(data, colWidths=[2.5*inch, 3.5*inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (1, 0), colors.HexColor('#eff6ff')),
            ('TEXTCOLOR', (0, 0), (1, 0), colors.HexColor('#1e40af')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#e5e7eb')),
        ]))
        story.append(t)
        story.append(Spacer(1, 20))

        # 3. Recommendations
        story.append(Paragraph("💡 Expert Recommendations", styles['SectionHeader']))
        
        # Process markdown-like bolding in recommendation text for the PDF
        rec_text = recommendation if recommendation else "No specific recommendation generated."
        clean_rec = rec_text.replace('**', '<b>').replace('**', '</b>').replace('*', '') 
        # Using a monospaced font or just standard paragraph for recommendations
        story.append(Paragraph(clean_rec.replace('\n', '<br/>'), styles['NormalText']))
        story.append(Spacer(1, 20))

        # 4. Required Documents Checklist
        story.append(Paragraph("📝 Required Documents Checklist", styles['SectionHeader']))
        docs_list = [
            "Identity Proof (Aadhar Card / Voter ID / Passport)",
            "Address Proof (Utility Bill / Rent Agreement)",
            "Income Proof (Salary Slips / ITR / Bank Statement)",
            "Passport Size Photographs",
            "Medical History Records (if applicable)"
        ]
        
        for doc_item in docs_list:
             story.append(Paragraph(f"• {doc_item}", styles['NormalText']))
             
        story.append(Spacer(1, 30))
        
        # 5. Footer
        story.append(Paragraph("<i>Disclaimer: This report is generated by an AI assistant. Please consult with a certified insurance advisor before making final decisions.</i>", styles['Normal']))

        try:
            doc.build(story)
            print(f"✅ PDF Generated Successfully: {filepath}")
        except Exception as e:
            print(f"❌ ReportLab Error: {e}")
            raise e
        
        return filename
