from fpdf import FPDF
import os

class InsuranceReport(FPDF):
    def header(self):
        # Logo placeholder (text for now)
        self.set_font('Arial', 'B', 15)
        self.cell(80)
        self.cell(30, 10, 'Personal Insurance Roadmap', 0, 0, 'C')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} | Generated by Suraksha Sahayak AI | IRDAI Compliance: Information is indicative.', 0, 0, 'C')

def generate_pdf_report(user_data: dict, recommendation: str, filename: str) -> str:
    """
    Generates a professional PDF report for the user.
    Returns: Absolute path to the generated PDF.
    """
    pdf = InsuranceReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Title
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, f'Insurance Plan for {user_data.get("name", "Valued Member")}', 0, 1, 'L')
    pdf.ln(5)
    
    # Profile Section
    pdf.set_font('Arial', 'B', 12)
    pdf.set_fill_color(200, 220, 255)
    pdf.cell(0, 10, '1. Member Profile', 0, 1, 'L', 1)
    pdf.set_font('Arial', '', 11)
    
    profile_text = (
        f"Name: {user_data.get('name')}\n"
        f"Age: {user_data.get('age')}\n"
        f"Occupation: {user_data.get('occupation')}\n"
        f"Dependents: {user_data.get('family')}\n"
        f"Key Worry: {user_data.get('worry')}"
    )
    pdf.multi_cell(0, 8, profile_text)
    pdf.ln(5)
    
    # Analysis Section
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, '2. Risk Analysis', 0, 1, 'L', 1)
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(0, 8, "Based on your profile, your primary risk category is 'Family Protection & Asset Security'. Investing in a plan that secures your family's future in your absence is critical.")
    pdf.ln(5)
    
    # Recommendation Section
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, '3. Recommended Policy', 0, 1, 'L', 1)
    pdf.set_font('Arial', '', 11)
    
    # Clean recommendation text (simple cleanup)
    clean_rec = recommendation.replace("*", "")
    pdf.multi_cell(0, 8, clean_rec)
    pdf.ln(5)
    
    # Compliance Section
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, '4. Next Steps & Compliance', 0, 1, 'L', 1)
    pdf.set_font('Arial', '', 10)
    pdf.multi_cell(0, 8, "1. Visit the nearest branch or bank.\n2. Carry your Aadhar Card and Pan Card.\n3. Show this report to the agent.\n\nDisclaimer: This is an AI-generated suggestion based on user input. Please read policy documents carefully before buying. Insurance is the subject matter of solicitation.")
    
    # Save
    static_dir = os.path.join(os.path.dirname(__file__), "../static/reports")
    os.makedirs(static_dir, exist_ok=True)
    
    file_path = os.path.join(static_dir, filename)
    pdf.output(file_path)
    
    return file_path
